// copyright 2013-2020 BAE Systems, Thales Group, Object Management Group Inc; 2013 Selex ES, DSTO, Atlas Elektronik, EADS Deutschland GmbH

#ifndef ORGOMGC4IDOMAIN_MODELRADAR_DOMAINAIR_ENGAGEMENT_SUPPORTDEFVAR
#define ORGOMGC4IDOMAIN_MODELRADAR_DOMAINAIR_ENGAGEMENT_SUPPORTDEFVAR
#include "Common_Types.idl"
#include "Coordinates_and_Positions.idl"
#include "Track_Reporting.idl"

module org
{

  module omg
  {

    module c4i
    {

      module Domain_Model
      {

        module Radar_Domain
        {

          module Air_Engagement_Support
          {

            @doc("Is sent once a hit or miss is noted.")
            struct miss_indication_data_type
            {
              @doc("Closest distance of the projectile to the target expressed in polar coordinates.")
              org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::polar_position_type miss_distance;
              @doc("Closest time of approach of the projectile to the target.")
              org::omg::c4i::Domain_Model::Common_Types::time_type time_stamp;
            };

            @doc("Identifies the kinematics of the projectile that is expected to hit the target.")
            struct projectile_kinematics_type
            {
              @doc("The timestamp when the kinematics was valid/measured.")
              org::omg::c4i::Domain_Model::Common_Types::time_type time_stamp;
              @doc("The projectile's position.")
              org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::position_coordinate_type position_descriptor;
              @doc("The projectile's velocity.")
              org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::velocity_coordinate_type velocity_descriptor;
            };

            @doc("Expected hit identifies the target and the time a hit is expected. This data is
                used to initiate the evaluation of a miss indication within the radar.")
            struct expected_hit_data_type
            {
              @doc("Time when projectile is expected to hit the target.")
              org::omg::c4i::Domain_Model::Common_Types::time_type expected_hit_time;
              @doc("The target track id.")
              org::omg::c4i::Domain_Model::Sensor_Domain::Track_Reporting::sensor_track_id_type track_id_descriptor;
              projectile_kinematics_type kinematics_descriptor;
            };

          };
        };
      };
    };
  };
};
#endif
