#ifndef CLUTTER_REPORTINGDEFVAR
#define CLUTTER_REPORTINGDEFVAR
#include "Shape_Model.idl"
#include "Common_Types.idl"


// Version 1.1
module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Sensor_Domain {


          module Clutter_Reporting {



            // CMS generated request for a clutter assessment.
            struct clutter_assessment_request_type
            {
            	// Region for which the CMS clutter request was generated.
            	org::omg::c4i::Domain_Model::Common_Types::Shape_Model::general_polar_volume_type requested_region;
            };
  




            // Indicates if the clutter within the cell is of a specific type.
            enum clutter_indication_type
            {
            	// LAND
            	LAND,
            	// SEA
            	SEA,
            	// WEATHER
            	WEATHER,
            	// NO_STATEMENT
            	NO_STATEMENT
            };
  




            // Indicates the intensity and type of clutter for a defined geometric type.
            struct clutter_map_cell_type
            {
            	// Indicates the boundaries of the cell for which clutter is being reported.
            	org::omg::c4i::Domain_Model::Common_Types::Shape_Model::general_polar_volume_type cell_boundaries;
            	// Indicates whether the clutter is LAND, SEA, WEATHER, or unspecified
            	// (NO_STATEMENT).
            	clutter_indication_type clutter_type;
            	// Intensity of the clutter for the specified cell. Units indicated by the
            	// intensity type attribute. 
            	double clutter_intensity;
            };
  




            // A sequence type, to represent multiple values. Note: variable length sequence,
            // which should contain at least one instance.
            typedef sequence<clutter_map_cell_type> clutter_report_clutter_map_cell_type;
  




            // Units of the clutter intensity
            enum intensity_units_type
            {
            	// POWER_RECEIVED_LINEAR
            	POWER_RECEIVED_LINEAR,
            	// POWER_RECEIVED_LOG_LINEAR
            	POWER_RECEIVED_LOG_LINEAR,
            	// RCS_LINEAR
            	RCS_LINEAR,
            	// RCS_LOG_LINEAR
            	RCS_LOG_LINEAR,
            	// SNR_LINEAR
            	SNR_LINEAR,
            	// SNR_LOG_LINEAR
            	SNR_LOG_LINEAR
            };
  




            // Clutter report generated by the subsystem. 
            struct clutter_report_type
            {
            	// Indicates the units of the clutter intensity reported.
            	intensity_units_type intensity_type;
            	// Time of the clutter report.
            	org::omg::c4i::Domain_Model::Common_Types::time_type time_of_report;
            	clutter_report_clutter_map_cell_type clutter_map_cell;
            };
  




            // Indicates the plot concentration of a defined geometric type.
            struct concentration_plot_cell_type
            {
            	// Specifies the dimension of the cell for which plot concentration is being
            	// reported.
            	org::omg::c4i::Domain_Model::Common_Types::Shape_Model::general_polar_volume_type cell_boundaries;
            	// The number of plots generated within the cell.
            	unsigned long long plot_count;
            	long _id;
            };
  




            // A sequence type, to represent multiple values. Note: variable length sequence,
            // which should contain at least one instance.
            typedef sequence<concentration_plot_cell_type> plot_concentration_report_concentration_plot_cell_type;
  




            // Plot concentration report as generated by the subsystem.
            struct plot_concentration_report_type
            {
            	// Time of the plot concentration report.
            	org::omg::c4i::Domain_Model::Common_Types::time_type time_of_report;
            	plot_concentration_report_concentration_plot_cell_type concentration_plot_cell;
            };
  




            // CMS request for plot concentration of a specified region.
            struct plot_concentration_request_data_type
            {
            	// Region for which the plot concentration was requested.
            	org::omg::c4i::Domain_Model::Common_Types::Shape_Model::general_polar_volume_type region_of_plot_concentration_request;
            };
  



          };
        };
      };
    };
  };
};
#endif