#ifndef COMMON_TYPESDEFVAR
#define COMMON_TYPESDEFVAR
#include "TimeBase.idl"


// Version 1.1
module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Common_Types {



          // Representation for a general binary type
          typedef sequence<octet, 1024> anonymous_blob_type;
  




          // Identity according to STANAG 5516.
          enum identity_type
          {
          	// PENDING
          	PENDING,
          	// UNKNOWN
          	UNKNOWN,
          	// ASSUMED_FRIEND
          	ASSUMED_FRIEND,
          	// FRIEND
          	FRIEND,
          	// NEUTRAL
          	NEUTRAL,
          	// SUSPECT
          	SUSPECT,
          	// HOSTILE
          	HOSTILE
          };
  




          // This type provides a unique id for different subsystems. Subsystem ids shall be
          // allocated by the platform integrator. Subsystem id equal to zero is reserved to
          // imply applicability to all and any subsystem.
          typedef unsigned short subsystem_id_type;
  




          // System Track Identification
          typedef unsigned long system_track_id_type;
  




          // based on start of Gregorian calendar (1582-10-15T 00:00UTC)
          //  unit: 100 nano seconds
          //  i.a.w CORBA Time Service Time T
          typedef TimeBase::TimeT time_type;
  



        };
      };
    };
  };
};
#endif