#ifndef CONTROL_RECORDINGDEFVAR
#define CONTROL_RECORDINGDEFVAR
#include "Common_Types.idl"
#include "Requests.idl"
#include "Recording_and_Replay.idl"


// Version 1.1
module org {


  module omg {


    module c4i {


      module Service_Interfaces {


        module Subsystem_Services {


          module Recording_and_Replay {


            module Control_Recording {



              // Topic type for operation define_recording_set. . Specifies what is to be
              // recorded
              struct define_recording_set_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              	// Field for interface operation parameter recording_parameters_list. 
              	org::omg::c4i::Domain_Model::Subsystem_Domain::Recording_and_Replay::recording_set_type recording_parameters_list;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist define_recording_set_type  subsystem_id
  




              // Topic type for operation start_recording. . Starts the recording as specified.
              // Note that only one recording may be running at a time.
              struct start_recording_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              	// Field for interface operation parameter id. 
              	org::omg::c4i::Domain_Model::Subsystem_Domain::Recording_and_Replay::recording_id_type id;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist start_recording_type  subsystem_id
  




              // Topic type for operation stop_recording. . Stops the recording
              struct stop_recording_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist stop_recording_type  subsystem_id
  



            };
          };
        };
      };
    };
  };
};
#endif