#ifndef ENCYCLOPAEDIC_SUPPORTDEFVAR
#define ENCYCLOPAEDIC_SUPPORTDEFVAR


// Version 1.1
module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Subsystem_Domain {


          module Encyclopaedic_Support {



            // Standard description of the encyclopaedic data set
            typedef string<60> data_descriptor_type;
  




            // Representation of a Uniform Resource Locator see www.w3.org
            typedef string<255> url_type;
  



          };
        };
      };
    };
  };
};
#endif