#ifndef EXTENDED_SUBSYSTEM_CONTROLDEFVAR
#define EXTENDED_SUBSYSTEM_CONTROLDEFVAR


// Version 1.1
module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Subsystem_Domain {


          module Extended_Subsystem_Control {



            // String which provides a url location for configuration data.
            typedef string<255> configuration_url_type;
  




            // Subsystem specific detailed test results
            typedef string<4096> offline_test_result_details_type;
  




            // Used to return the test results: failed, partial_pass or failed
            enum offline_test_result_type
            {
            	// FAILED
            	FAILED,
            	// PARTIAL_PASS
            	PARTIAL_PASS,
            	// PASSED
            	PASSED
            };
  




            // A subsystem specific string identifying the required test type.
            typedef string<255> offline_test_type;
  



          };
        };
      };
    };
  };
};
#endif