#ifndef PERFORM_ILLUMINATIONDEFVAR
#define PERFORM_ILLUMINATIONDEFVAR
#include "Common_Types.idl"

#include "Requests.idl"

#include "Missile_Guidance.idl"


module org {


  module omg {


    module c4i {


      module Service_Interfaces {


        module Radar_Services {


          module Missile_Guidance {


            module Perform_Illumination {



              // Version 1.0
              // Topic type for operation complete. This service covers the control of target
              // illumination to support a semi-active homing missile engagement.
              // 
              //      The actor is the Combat Management System.
              // 
              //      The service is triggered by the illumination request of the actor.
              // Typically, illumination takes place during a specific period within the
              // engagement sequence.
              //      The actor sends an illumination request to the radar.
              //      On the requested start time, the radar starts illuminating the target with
              // specified parameters.
              //      During the illumination, the actor may provide updates of illumination
              // parameters, e.g. to change the stop time.
              //      The service ends at stop time of the illumination.
              // 
              //      If the radar may not fulfil the illumination request, this is reported to
              // the actor and the service stops.
              // 
              //      If during the illumination a radar fault takes place that prevents
              // execution of illumination (e.g. illumination frequency not more available),
              // the health state of the Missile Guidance service (of which this service is
              // part) becomes DEGRADED (if the Missile Guidance service is still capable of
              // performing uplinks and/or downlinks) or NOT AVAILABLE, and the service stops.
              // 
              //      If the target track becomes lost during the illumination, the service
              // stops.. 
              struct complete_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              };
#pragma keylist complete_type 
  




              // Version 1.0
              // Topic type for operation receive_error. This service covers the control of
              // target illumination to support a semi-active homing missile engagement.
              // 
              //      The actor is the Combat Management System.
              // 
              //      The service is triggered by the illumination request of the actor.
              // Typically, illumination takes place during a specific period within the
              // engagement sequence.
              //      The actor sends an illumination request to the radar.
              //      On the requested start time, the radar starts illuminating the target with
              // specified parameters.
              //      During the illumination, the actor may provide updates of illumination
              // parameters, e.g. to change the stop time.
              //      The service ends at stop time of the illumination.
              // 
              //      If the radar may not fulfil the illumination request, this is reported to
              // the actor and the service stops.
              // 
              //      If during the illumination a radar fault takes place that prevents
              // execution of illumination (e.g. illumination frequency not more available),
              // the health state of the Missile Guidance service (of which this service is
              // part) becomes DEGRADED (if the Missile Guidance service is still capable of
              // performing uplinks and/or downlinks) or NOT AVAILABLE, and the service stops.
              // 
              //      If the target track becomes lost during the illumination, the service
              // stops.. 
              struct receive_error_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              	// Field for interface operation parameter error_reason. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::error_reason_type error_reason;
              };
#pragma keylist receive_error_type 
  




              // Version 1.0
              // Topic type for operation request_illumination. . 
              struct request_illumination_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              	// Field for interface operation parameter request. 
              	org::omg::c4i::Domain_Model::Radar_Domain::Missile_Guidance::illumination_request_type request;
              };
#pragma keylist request_illumination_type 
  



            };
          };
        };
      };
    };
  };
};
#endif