#ifndef PROVIDE_SENSOR_ORIENTATIONDEFVAR
#define PROVIDE_SENSOR_ORIENTATIONDEFVAR
#include "Common_Types.idl"
#include "Plot_Reporting.idl"


// Version 1.1
module org {


  module omg {


    module c4i {


      module Service_Interfaces {


        module Sensor_Services {


          module Plot_Reporting {


            module Provide_Sensor_Orientation {



              // Topic type for operation write_sensor_orientation. The interface to the CMS for
              // receiving sensor orientation updates.
              //      The sensor provides its orientation in the case that it has movement that
              // is independent of that for the overall platform. It is provided periodically
              // with a frequency defined using the manage subsystem parameters use case..
              // Informs the CMS of the orientation of the sensor
              struct write_sensor_orientation_type
              {
              	// Field for interface operation parameter orientation. The orientation of the
              	// sensor
              	org::omg::c4i::Domain_Model::Sensor_Domain::Plot_Reporting::sensor_orientation_type orientation;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist write_sensor_orientation_type  subsystem_id
  



            };
          };
        };
      };
    };
  };
};
#endif