#ifndef RECEIVE_TRACK_INFORMATIONDEFVAR
#define RECEIVE_TRACK_INFORMATIONDEFVAR
#include "Common_Types.idl"

#include "Tracking_Control.idl"

#include "Requests.idl"

#include "Track_Reporting.idl"


module org {


  module omg {


    module c4i {


      module Service_Interfaces {


        module Sensor_Services {


          module Tracking_Control {


            module Receive_Track_Information {



              // Version 1.0
              // Topic type for operation insert_info_track. This is the Subsystem interface for
              // receiving track information.. Method used by the CMS to send a receive track
              // information request, specifying the track identification number and related
              // track information.
              struct insert_info_track_type
              {
              	// Field for interface operation parameter request_id. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type request_id;
              	// Field for interface operation parameter trackId. 
              	org::omg::c4i::Domain_Model::Sensor_Domain::Track_Reporting::sensor_track_id_type trackId;
              	// Field for interface operation parameter trackInfo. 
              	org::omg::c4i::Domain_Model::Sensor_Domain::Tracking_Control::track_info trackInfo;
              };
#pragma keylist insert_info_track_type 
  



            };
          };
        };
      };
    };
  };
};
#endif