#ifndef SEARCHDEFVAR
#define SEARCHDEFVAR
#include "Coordinates_and_Positions.idl"

#include "Shape_Model.idl"

#include "Track_Reporting.idl"


module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Radar_Domain {


          module Search {



            // Version 1.0
            // a simple union type, to represent an optional value
            union cued_search_cue_speed_interval_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::speed_interval_type value;
            };
  




            // Version 1.0
            // Type used for specifying the constraints on a cued search.
            struct cued_search_cue_type
            {
            	// The range of track-speed to search for from the cue.
            	cued_search_cue_speed_interval_type speed_interval;
            	// The region in the environment, in which the cue to search for tracks is to be
            	// performed.
            	org::omg::c4i::Domain_Model::Common_Types::Shape_Model::general_polar_volume_type volume;
            	// The orientation of the polar coordinates used in this class. Note that the
            	// origin is always the sensor reference point and that the coordinate system is
            	// always polar.
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::coordinate_orientation_type coordinate_orientation;
            };
  




            // Version 1.0
            // a simple union type, to represent an optional value
            union cued_search_report_found_track_id_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Sensor_Domain::Track_Reporting::sensor_track_id_type value;
            };
  




            // Version 1.0
            // Data returned to the CMS to indicate the results of a cued search.
            struct cued_search_report_type
            {
            	cued_search_report_found_track_id_type found_track_id;
            	long original_cue_id;
            };
  



          };
        };
      };
    };
  };
};
#endif