#ifndef SHAPE_MODELDEFVAR
#define SHAPE_MODELDEFVAR
#include "Coordinates_and_Positions.idl"


module org {


  module omg {


    module c4i {


      module Domain_Model {


        module Common_Types {


          module Shape_Model {



            // Version 1.0
            // A figure_ref_point specifies a reference point for a figure.
            //    This reference point is a mathematically meaningful point of the figure. For
            // a circle it is the centre of the circle, for a polygon it is the centre of
            // gravity of the polygon, etc.
            // 
            //    When rotating the figure, the figure_ref_point acts as the rotation point.
            // 
            //    When a figure is not slaved to a track its figure_ref_point shall be mapped
            // on a (moving) geo point.
            //    When the figure is slaved to an object (track, point) its figure_ref_point
            // shall be mapped on an offset position which is relative to the master object.
            struct figure_ref_point
            {
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::position_coordinate_type position;
            };
  




            // Version 1.0
            // Switch enumeration type for union general_polar_volume_type
            enum general_polar_volume_switch_type
            {
            	// The general_polar_volume_type union contains a value of sector_type
            	general_polar_volume_type_sector_kind,
            	// The general_polar_volume_type union contains a value of polar_volume_type
            	general_polar_volume_type_polar_volume_kind,
            	// The general_polar_volume_type union contains a value of truncated_sector_type
            	general_polar_volume_type_truncated_sector_kind,
            	// The general_polar_volume_type union contains a value of
            	// truncated_polar_volume_type
            	general_polar_volume_type_truncated_polar_volume_kind
            };
  




            // Version 1.0
            // a simple union type, to represent an optional value
            union sector_origin_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::figure_ref_point value;
            };
  




            // Version 1.0
            // A sector specifies a 2D area in a horizontal plane by means of its origin, its
            // centre bearing with its bearing delta, that together define the sector.
            //    The origin is the figure reference point of the sector.
            //    In case the sector is north oriented, the centre bearing is specified with
            // respect to true north; otherwise it is specified with respect to the object's
            // (own ship/other track, point) heading/course.
            struct sector_type
            {
            	// This attribute specifies the horizontal angle measured clockwise between the Y-
            	// axis of the relevant coordinate system (true north, heading/course) and the
            	// centre bearing line of the sector.
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type centre_bearing;
            	// This attribute specifies the bearing delta on each side of a specified centre
            	// bearing line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type delta_bearing;
            	sector_origin_type origin;
            };
  




            // Version 1.0
            // a simple union type, to represent an optional value
            union polar_volume_origin_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::figure_ref_point value;
            };
  




            // Version 1.0
            // A polar_volume specifies a 3D volume based on a horizontal plane by means of
            // its origin, its centre bearing and centre elevation, its bearing delta and
            // elevation delta.
            //    The origin is the figure reference point of the Polar Volume.
            struct polar_volume_type
            {
            	// This attribute specifies the horizontal angle measured clockwise between the Y-
            	// axis of the relevant coordinate system (true north, heading/course) and the
            	// centre bearing line of the volume. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type centre_bearing;
            	// This attribute specifies the bearing delta on each side of a specified centre
            	// bearing line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type delta_bearing;
            	// This attribute specifies the vertical angle measured counterclockwise between
            	// the horizontal plane and the centre elevation line of the volume. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::elevation_coordinate_type centre_elevation;
            	// This attribute specifies the elevation delta on each side of a specified centre
            	// elevation line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::elevation_coordinate_type delta_elevation;
            	polar_volume_origin_type origin;
            };
  




            // Version 1.0
            // a simple union type, to represent an optional value
            union truncated_sector_origin_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::figure_ref_point value;
            };
  




            // Version 1.0
            // A truncated_sector specifies a 2D area in a horizontal plane by means of its
            // origin, its centre bearing with its bearing delta, and its inner range and
            // outer range, that together define the truncated sector.
            //    The origin is the figure reference point of the truncated sector.
            //    In case the truncated sector is north oriented, the centre bearing is
            // specified with respect to true north; otherwise (object oriented) it is
            // specified with respect to the object's (own ship/other track, point)
            // heading/course.
            struct truncated_sector_type
            {
            	// This attribute specifies the horizontal angle measured clockwise between the Y-
            	// axis of the relevant coordinate system (true north, heading/course) and the
            	// centre bearing line of the truncated sector. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type centre_bearing;
            	// This attribute specifies the bearing delta on each side of a centre bearing
            	// line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type delta_bearing;
            	// This attribute specifies the range that limits a truncated sector; i.e. the
            	// minimum distance from the truncated sector's origin. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::range_coordinate_type inner_range;
            	// This attribute specifies the range that limits a truncated sector; i.e. the
            	// maximum distance from the truncated sector's origin.
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::range_coordinate_type outer_range;
            	truncated_sector_origin_type origin;
            };
  




            // Version 1.0
            // a simple union type, to represent an optional value
            union truncated_polar_volume_origin_type switch (boolean)
            {
            	// the value when present
            	case TRUE : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::figure_ref_point value;
            };
  




            // Version 1.0
            // A truncated_polar_volume specifies a 3D volume based on a horizontal plane by
            // means of its origin, its centre bearing and centre elevation, its bearing delta
            // and elevation delta, its inner range and outer range
            struct truncated_polar_volume_type
            {
            	// This attribute specifies the horizontal angle measured clockwise between the Y-
            	// axis of the relevant coordinate system (true north, heading/course) and the
            	// centre bearing line of the volume. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type centre_bearing;
            	// This attribute specifies the bearing delta on each side of a specified centre
            	// bearing line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::azimuth_coordinate_type delta_bearing;
            	// This attribute specifies the vertical angle measured counterclockwise between
            	// the horizontal plane and the centre elevation line of the volume.
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::elevation_coordinate_type centre_elevation;
            	// This attribute specifies the elevation delta on each side of a specified centre
            	// elevation line. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::elevation_coordinate_type delta_elevation;
            	// This attribute specifies the range that limits a volume; i.e. the minimum
            	// distance from the volume's origin.
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::range_coordinate_type inner_range;
            	// This attribute specifies the range that limits a volume; i.e. the maximum
            	// distance from the volume's origin. 
            	org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::range_coordinate_type outer_range;
            	truncated_polar_volume_origin_type origin;
            };
  




            // Version 1.0
            // This class allow definition of a volume in space, bounded by standard polar
            // coordinates (azimuth, elevation and range). The different options allow the
            // dimension of either range, elevation or both to be omitted.
            union general_polar_volume_type switch (general_polar_volume_switch_type)
            {
            	// The general polar volume is a sector
            	case general_polar_volume_type_sector_kind : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::sector_type sector;
            	// The general polar volume is a polar volume
            	case general_polar_volume_type_polar_volume_kind : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::polar_volume_type polar_volume;
            	// The general polar volume is a truncated sector
            	case general_polar_volume_type_truncated_sector_kind : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::truncated_sector_type truncated_sector;
            	// The general polar volume is a truncated polar volume.
            	case general_polar_volume_type_truncated_polar_volume_kind : org::omg::c4i::Domain_Model::Common_Types::Shape_Model::truncated_polar_volume_type truncated_polar_volume;
            };
  



          };
        };
      };
    };
  };
};
#endif