#ifndef SUPPORT_KILL_ASSESSMENTDEFVAR
#define SUPPORT_KILL_ASSESSMENTDEFVAR
#include "Common_Types.idl"
#include "Requests.idl"
#include "Engagement_Support.idl"
#include "Air_Engagement_Support.idl"


// Version 1.1
module org {


  module omg {


    module c4i {


      module Service_Interfaces {


        module Radar_Services {


          module Engagement_Support {


            module Support_Kill_Assessment {



              // Topic type for operation report_kill_assessment_result. With this service the
              // subsystem provides of kill assessment information to the CMS. The information
              // relates to an above water engagement primarily against an air target.
              // 
              //      The kill assessment report of the subsystem may be one of the three:
              //      <ul>
              //      	<li>PROBABLE-KILL. This indicates that the subsystem assumes the target
              // to be killed.</li>
              //      	<li>PROBABLE-MISS. This indicates that the subsystem assumes the target
              // to be missed by the used weapon system. </li>
              //      	<li>NO-RESULT. This indicates that the subsystem was not able to
              // determine a valid result for this request. </li>
              //      </ul>
              // 
              //      See also service (interface) "Process Target Designation".. Via this
              // message, the subsystem reports the kill assessment to the CMS.
              struct report_kill_assessment_result_type
              {
              	// Field for interface operation parameter RequestID. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type RequestID;
              	// Field for interface operation parameter KillAssessmentReport. 
              	org::omg::c4i::Domain_Model::Radar_Domain::Engagement_Support::kill_assessment_result_type KillAssessmentReport;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist report_kill_assessment_result_type  subsystem_id
  




              // Topic type for operation request_kill_assessment. . The subsystem is requested
              // to evaluate and report a kill assessment.
              struct request_kill_assessment_type
              {
              	// Field for interface operation parameter RequestID. 
              	org::omg::c4i::Domain_Model::Common_Types::Requests::request_id_type RequestID;
              	// Field for interface operation parameter KillAssessmentData. 
              	org::omg::c4i::Domain_Model::Radar_Domain::Air_Engagement_Support::expected_hit_data_type KillAssessmentData;
              // Indicates which subsystem published the data or is intended to read it as a subscriber
#ifdef DDS_XTYPES
              @Key org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#else
              org::omg::c4i::Domain_Model::Common_Types::subsystem_id_type subsystem_id;
#endif
              };
#pragma keylist request_kill_assessment_type  subsystem_id
  



            };
          };
        };
      };
    };
  };
};
#endif